Sumo 110
war-in/SumoServer pull request #10
Opened 2022-07-09 11:03 UTC by Gajkes

2022-07-12 15:28 UTC, war-in requested changes
Ogólnie w porządku, ale chyba nie ma sensu tworzyć klasy CompetitionJson i CompetitionToJson (chyba, że jest to chętnie usłyszę). Mam nadzieję na odpowiedzi na pytania zadane w komentarzach, bo w paru miejscach nie wiem, czemu tak zostało to zrobione.

2022-07-12 15:28 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionJson.java
> +}
Tutaj można ogarnąć przestrzenie pomiędzy poszczególnymi polami, bo raczej nie potrzebujemy ich aż tyle

2022-07-12 15:28 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionToJson.java
> +package com.sumo.server.Database.CompetitionData.Competition;
Zgadzam się, raczej nie trzeba dokładać takich klas

2022-07-12 15:28 UTC, war-in commented on src/main/java/com/sumo/server/Database/StaticData/City/City.java
> +    @JsonManagedReference
Co to za adnotacja? Nie widziałem takich wcześniej, więc chętnie usłyszę co ono robi

2022-07-12 15:28 UTC, war-in commented on src/main/java/com/sumo/server/Database/TeamData/NationalTeam/NationalTeamRepository.java
> +    NationalTeam findNationalTeamByCountryEquals(Country country);
W jakim celu jest tu Equals na końcu?

2022-07-12 15:28 UTC, war-in commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +
Chyba obejdziemy się bez tej linijki

2022-07-12 15:28 UTC, war-in commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +        }).toList();
Tak jak pisał wcześniej Kuba, jesteśmy w stanie to ominąć korzystając z mapowania gsonem

2022-07-12 15:28 UTC, war-in commented on src/main/java/com/sumo/server/apis/NationalTeams/NationalTeamController.java
> +
Można usunąć taką pustą linijkę

2022-07-12 15:29 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionToJson.java
> +package com.sumo.server.Database.CompetitionData.Competition;
Zgadzam się, raczej nie potrzebujemy takich klas

2022-07-20 17:11 UTC, Gajkes commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionToJson.java
> +package com.sumo.server.Database.CompetitionData.Competition;
Ok tutaj chciałem rozbić jakoś logike moze przekobinowałem dało sie to prościej zrobic.

2022-07-20 17:15 UTC, Gajkes commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionToJson.java
> +package com.sumo.server.Database.CompetitionData.Competition;
> 



> napewno potrzebujemy klasy konwertującej pomiędzy obiektami, do tej pory kożystaliśmy w projekcie z gsona i on całkiem nieźle sprawdzał się do serializacji klas kiedy json wygląda 1:1 jak pierwotna klasa

Dobra to zamieniam na zwracanie całej klasy i automatyczne mapowanie na jsona przez springa

2022-07-20 17:33 UTC, Gajkes commented
Poprawiłem te rzeczy o których pisaliście dajcie info czy mozna mergować

2022-07-23 22:01 UTC, sumo-slonik commented
jak dla mnie jest już ok

2022-07-24 13:10 UTC, merged