Serwis do zawodów
war-in/SumoServer pull request #4
Opened 2022-05-15 16:23 UTC by sumo-slonik

2022-05-17 07:09 UTC, war-in requested changes

2022-05-17 07:09 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        return competitionRepository.findAllBy();
Czy to na 100% zadziała? W innym projekcie przy użyciu findAllBy nie dostawałem oczekiwanej odpowiedzi. Pomogło użycie findAll, ale jeśli było to testowane to ok

2022-05-17 07:09 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +    public Competition addCategoriesToCompetitions(List<Category> categoryList, Competition competition) {
Można zmienić na "addCategoriesToCompetition"

2022-05-17 07:09 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        return competitionDetailsRepository.save(competitionDetails);
Wcześniej przy każdym użyciu save pojawiało się try/catch. Czy tutaj nie powinno być podobnie? A jeśli nie to, czy tam jest to konieczne?

2022-05-17 07:09 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        return competitionTypeRepository.save(competitionType);
Tu podobnie jak wyżej

2022-05-17 07:09 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        competition.setDetails(competitionDetails);
Niżej na początku wyciągamy competition z bazy i późniejsze akcje wykonujemy na tym wyciągniętym obiekcie. Myślę, że to dobra praktyka i tutaj też sugerowałbym takie podejście

2022-05-17 07:09 UTC, war-in commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        competition.setType(competitionType);
Tak jak wyżej

2022-05-17 08:27 UTC, war-in commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +        return ResponseEntity.ok().build();
Podejrzewam, że tu zapomniałeś o wsadzeniu uri do response entity

2022-05-18 20:19 UTC, sumo-slonik commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +    public ResponseEntity<Competition> saveCompetition(@RequestBody Competition competition) {
będę dodawał w notatkach
zamieszczę link jak zrobię

2022-05-18 20:19 UTC, sumo-slonik commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +        return ResponseEntity.created(uri).body(competitionService.addDetailsToCompetitions(competition, competitionDetails, competitionType));
masz rację

2022-05-18 20:19 UTC, sumo-slonik commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +    public ResponseEntity<Competition> saveCompetition(@RequestBody Competition competition) {
jw

2022-05-18 20:20 UTC, sumo-slonik commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +        return ResponseEntity.created(uri).body(competitionService.addDetailsToCompetitions(competition, competitionDetails, competitionType));
jw

2022-05-18 20:20 UTC, sumo-slonik commented on src/test/java/com/sumo/server/Apis/Competition/CompetitionControllerTest.java
> +        assert competitions.stream().allMatch(o -> firstIterator.hasNext() && o.equals(firstIterator.next())) && !firstIterator.hasNext();
poprawię

2022-05-18 20:20 UTC, sumo-slonik commented on src/test/java/com/sumo/server/Apis/Competition/CompetitionControllerTest.java
> +
+1

2022-05-18 20:21 UTC, sumo-slonik commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        return competitionRepository.findAllBy();
testowałem i działa ale upewnię się jeszcze raz, ale zmienię i tak żeby nie było by

2022-05-18 20:21 UTC, sumo-slonik commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +    public Competition addCategoriesToCompetitions(List<Category> categoryList, Competition competition) {
jw

2022-05-18 20:21 UTC, sumo-slonik commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        return competitionDetailsRepository.save(competitionDetails);
powinno dodam

2022-05-18 20:21 UTC, sumo-slonik commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        return competitionTypeRepository.save(competitionType);
jw

2022-05-18 20:22 UTC, sumo-slonik commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        competition.setDetails(competitionDetails);
tutaj założyłem już że przy dodawaniu detali otrzymamy pełny element, bo to ten który wyżej pobieramy z bazy

2022-05-18 20:22 UTC, sumo-slonik commented on src/main/java/com/sumo/server/Database/CompetitionData/Competition/CompetitionServiceImpl.java
> +        competition.setType(competitionType);
jw

2022-05-18 20:22 UTC, sumo-slonik commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +        return ResponseEntity.ok().build();
+1

2022-05-22 12:39 UTC, war-in commented on src/main/java/com/sumo/server/apis/Competitions/CompetitionController.java
> +        return ResponseEntity.ok().build();
z tego co widziałem to to nadal nie jest poprawione xd Przeoczenie?

2022-05-30 16:43 UTC, merged