SUMO-65
war-in/SumoServer pull request #5
Opened 2022-05-16 20:26 UTC by Gajkes

2022-05-17 07:16 UTC, war-in requested changes
Ogólnie spoko, tylko w sumie niewiadomo, czy było to testowane, czy nie. Raczej pasuje napisać przynajmniej jeden podstawowy test, a na 100% ręcznie postmanem sprawdzić działanie wszystkich endpointów

2022-05-17 07:16 UTC, war-in commented on src/main/java/com/sumo/server/Database/RegistrationAndWeightData/WeighedCompetitor/WeighedCompetitorServiceImpl.java
> +        return weighedCompetitorRepository.findAllBy();
Mamy pewność, że to działa? W innym projekcie zamiast tego musiałem użyć .findAll, które jest automatycznie stworzone przez JpaRepository.

2022-05-17 07:16 UTC, war-in commented on src/main/java/com/sumo/server/apis/weighting/WeightingController.java
> +    public void saveWeighting(@RequestBody WeighedCompetitor weighedCompetitor) {
Dobrze byłoby napisać czego oczekujemy w jsonie, który przyjdzie, żeby uniknąć późniejszych błędów

2022-05-31 18:08 UTC, Gajkes commented on src/main/java/com/sumo/server/Database/RegistrationAndWeightData/WeighedCompetitor/WeighedCompetitorServiceImpl.java
> +        return weighedCompetitorRepository.findAllBy();
masz racje

2022-06-05 18:28 UTC, war-in approved these changes

2022-07-04 21:11 UTC, merged